board_commitment = "0" # For proving, this will be calculated; for verification, use the actual commitment
salt = "643545130811632" # Use a random number as salt

# Carrier - Length 5
[[ships]]
start_x = "2"
start_y = "9"
end_x = "6"
end_y = "9"

# Battleship - Length 4
[[ships]]
start_x = "0"
start_y = "3"
end_x = "0"
end_y = "6"

# Cruiser - Length 3
[[ships]]
start_x = "4"
start_y = "6"
end_x = "4"
end_y = "8"

# Submarine - Length 3
[[ships]]
start_x = "5"
start_y = "1"
end_x = "5"
end_y = "3"

# Destroyer - Length 2
[[ships]]
start_x = "9"
start_y = "5"
end_x = "9"
end_y = "6"

