[profile.default]
auto_detect_solc = true
src = "src"
out = "out"
libs = ["lib"]
test = "test"
bytecode_hash = "none"
cbor_metadata = false
optimizer = true
optimizer_runs = 1_000_000
viaIR = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
number_underscore = "thousands"

[rpc_endpoints]
MegaTestnet = "${MEGA_TESTNET_RPC_URL}"