[profile.default]
auto_detect_solc = true
src = "src"
out = "out"
libs = ["lib"]
test = "test"
bytecode_hash = "none"
cbor_metadata = false
optimizer = true
optimizer_runs = 1_000_000
# Increase the EVM stack size limit
evm_version = "cancun"
optimizer_details = { jumpdest_remover = true, order_literals = true, deduplicate = true, cse = true, constant_optimizer = true, yul = true }
viaIR = true
gas_reports = ["*"]
solc = "0.8.29"

exclude_paths = [
  "src/verifiers/*.sol"
]

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
MEGAETH = "${MEGA_TESTNET_RPC_URL}"