board_commitment = "0" # Will be calculated for proving
salt = "12345"
shot_x = "2"
shot_y = "0"
is_hit = "true"

# Carrier - Length 5
[[ships]]
start_x = "0"
start_y = "0"
end_x = "4"
end_y = "0"

# Battleship - Length 4
[[ships]]
start_x = "0"
start_y = "2"
end_x = "3"
end_y = "2"

# Cruiser - Length 3
[[ships]]
start_x = "5"
start_y = "5"
end_x = "7"
end_y = "5"

# Submarine - Length 3
[[ships]]
start_x = "9"
start_y = "0"
end_x = "9"
end_y = "2"

# Destroyer - Length 2
[[ships]]
start_x = "3"
start_y = "7"
end_x = "4"
end_y = "7"