board_commitment = "0" # Will be calculated for proving
salt = "947555887357673"
shot_x = "8"
shot_y = "5"
is_hit = "false"

# Carrier - Length 5
[[ships]]
start_x = "2"
start_y = "2"
end_x = "2"
end_y = "6"

# Battleship - Length 4
[[ships]]
start_x = "0"
start_y = "2"
end_x = "0"
end_y = "5"

# Cruiser - Length 3
[[ships]]
start_x = "5"
start_y = "9"
end_x = "7"
end_y = "9"

# Submarine - Length 3
[[ships]]
start_x = "3"
start_y = "5"
end_x = "5"
end_y = "5"

# Destroyer - Length 2
[[ships]]
start_x = "1"
start_y = "1"
end_x = "2"
end_y = "1"

