board_commitment = ""
salt = ""
shot_history_hash = ""

[[ships]]
end_x = ""
end_y = ""
start_x = ""
start_y = ""

[[ships]]
end_x = ""
end_y = ""
start_x = ""
start_y = ""

[[ships]]
end_x = ""
end_y = ""
start_x = ""
start_y = ""

[[ships]]
end_x = ""
end_y = ""
start_x = ""
start_y = ""

[[ships]]
end_x = ""
end_y = ""
start_x = ""
start_y = ""

[[shots]]
x = ""
y = ""

[[shots]]
x = ""
y = ""

[[shots]]
x = ""
y = ""

[[shots]]
x = ""
y = ""

[[shots]]
x = ""
y = ""

[[shots]]
x = ""
y = ""

[[shots]]
x = ""
y = ""

[[shots]]
x = ""
y = ""

[[shots]]
x = ""
y = ""

[[shots]]
x = ""
y = ""

[[shots]]
x = ""
y = ""

[[shots]]
x = ""
y = ""

[[shots]]
x = ""
y = ""

[[shots]]
x = ""
y = ""

[[shots]]
x = ""
y = ""

[[shots]]
x = ""
y = ""

[[shots]]
x = ""
y = ""
