board_commitment = "0" # Will be calculated for proving
salt = "12345"
shot_history_hash = "0" # Will be calculated for proving

# Carrier - Length 5
[[ships]]
start_x = "0"
start_y = "0"
end_x = "4"
end_y = "0"

# Battleship - Length 4
[[ships]]
start_x = "0"
start_y = "2"
end_x = "3"
end_y = "2"

# Cruiser - Length 3
[[ships]]
start_x = "5"
start_y = "5"
end_x = "7"
end_y = "5"

# Submarine - Length 3
[[ships]]
start_x = "9"
start_y = "0"
end_x = "9"
end_y = "2"

# Destroyer - Length 2
[[ships]]
start_x = "3"
start_y = "7"
end_x = "4"
end_y = "7"

# Shots that hit all ships (total 17 shots)
# Carrier hits (5)
[[shots]]
x = "0"
y = "0"

[[shots]]
x = "1"
y = "0"

[[shots]]
x = "2"
y = "0"

[[shots]]
x = "3"
y = "0"

[[shots]]
x = "4"
y = "0"

# Battleship hits (4)
[[shots]]
x = "0"
y = "2"

[[shots]]
x = "1"
y = "2"

[[shots]]
x = "2"
y = "2"

[[shots]]
x = "3"
y = "2"

# Cruiser hits (3)
[[shots]]
x = "5"
y = "5"

[[shots]]
x = "6"
y = "5"

[[shots]]
x = "7"
y = "5"

# Submarine hits (3)
[[shots]]
x = "9"
y = "0"

[[shots]]
x = "9"
y = "1"

[[shots]]
x = "9"
y = "2"

# Destroyer hits (2)
[[shots]]
x = "3"
y = "7"

[[shots]]
x = "4"
y = "7"