name: Foundry CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Run pre-build script if exists
        run: |
          if [ -f "./pre-build.sh" ]; then
            chmod +x ./pre-build.sh
            ./pre-build.sh
          fi
      
      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build
      
      - name: Run Forge tests
        run: |
          forge test -v
        id: test
      
      - name: Run Forge coverage
        run: |
          forge coverage
        id: coverage
      
      - name: Install Solhint
        run: |
          bun add --dev solhint
      
      - name: Run Solhint
        run: |
          npx solhint 'src/**/*.sol'